# Generated by Django 4.2.4 on 2023-08-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('deadline', models.DateTimeField()),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('point', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatusLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_user_status_links', to='db.user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status_links', to='db.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='db.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_links', to='db.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_lead', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.user')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_statuses', to='db.user'),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', on_delete=django.db.models.deletion.CASCADE, related_name='updated_statuses', to='db.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_roles', to='db.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', on_delete=django.db.models.deletion.CASCADE, related_name='updated_roles', to='db.user'),
        ),
        migrations.CreateModel(
            name='ProjectTeamLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.teams')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.teams'),
        ),
    ]
