# Generated by Django 4.2.4 on 2023-08-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_role_status_teamlink_teams_user_userrolelink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.teams')),
            ],
        ),
    ]
