# Generated by Django 4.2.4 on 2023-08-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_project_created_at_remove_project_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
