# Generated by Django 4.2.4 on 2023-08-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuserlink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskuserlink',
            name='updated_at',
        ),
    ]
