# Generated by Django 4.2.4 on 2023-08-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_remove_taskuserlink_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='teamlink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userrolelink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userstatuslink',
            name='created_at',
        ),
    ]
